//! Wire-format compatibility fixtures.
//!
//! The `.dt` files in `tests/fixtures/dt-v1/` were generated by the
//! generator test below while kutl-core still depended on crates.io
//! diamond-types 1.0.0. The loader test must keep passing across
//! diamond-types upgrades: the on-disk format is the compatibility
//! contract with every already-persisted document.

use std::path::PathBuf;

use kutl_core::Engine;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/dt-v1")
}

/// Regenerate fixtures:
/// `KUTL_WRITE_WIRE_FIXTURES=1 cargo test -p kutl-core --test wire_fixtures`
/// Only run this under the dt version whose output you intend to pin.
#[test]
fn generate_fixtures() {
    if std::env::var("KUTL_WRITE_WIRE_FIXTURES").is_err() {
        return;
    }
    std::fs::create_dir_all(fixture_dir()).expect("create fixture dir");
    let write = |name: &str, engine: &Engine| {
        std::fs::write(
            fixture_dir().join(format!("{name}.dt")),
            engine.encode_full(),
        )
        .expect("write .dt fixture");
        std::fs::write(fixture_dir().join(format!("{name}.txt")), engine.content())
            .expect("write .txt fixture");
    };

    // simple: ascii edits including deletes and mid-document inserts.
    let mut simple = Engine::new();
    let a = simple.get_or_create_agent("alice");
    simple.insert(a, 0, "hello world\n").expect("insert");
    simple.insert(a, 6, "cruel ").expect("insert");
    simple.delete(a, 0..6).expect("delete");
    simple.insert(a, 0, "goodbye ").expect("insert");
    write("simple", &simple);

    // unicode: multi-byte chars around the edit positions.
    let mut unicode = Engine::new();
    let a = unicode.get_or_create_agent("alice");
    unicode.insert(a, 0, "héllo 世界 🎉\n").expect("insert");
    unicode.insert(a, 6, "wide 全角 ").expect("insert");
    unicode.delete(a, 0..2).expect("delete");
    write("unicode", &unicode);

    // concurrent: two agents editing concurrently, merged both ways.
    let mut e1 = Engine::new();
    let a1 = e1.get_or_create_agent("alice");
    e1.insert(a1, 0, "base text here\n").expect("insert");
    let mut e2 = Engine::load_from(&e1.encode_full()).expect("bootstrap e2");
    let a2 = e2.get_or_create_agent("bob");
    e1.insert(a1, 0, "A>").expect("insert");
    e2.insert(a2, 4, "<B>").expect("insert");
    e2.delete(a2, 0..1).expect("delete");
    e1.merge_bytes(&e2.encode_full()).expect("merge e2 into e1");
    e2.merge_bytes(&e1.encode_full()).expect("merge e1 into e2");
    assert_eq!(e1.content(), e2.content(), "generator arms must converge");
    write("concurrent", &e1);
}

#[test]
fn fixtures_load_and_match() {
    for name in ["simple", "unicode", "concurrent"] {
        let bytes = std::fs::read(fixture_dir().join(format!("{name}.dt")))
            .unwrap_or_else(|e| panic!("missing fixture {name}.dt: {e}"));
        let expected = std::fs::read_to_string(fixture_dir().join(format!("{name}.txt")))
            .unwrap_or_else(|e| panic!("missing fixture {name}.txt: {e}"));
        let engine = Engine::load_from(&bytes)
            .unwrap_or_else(|e| panic!("fixture {name}.dt failed to load: {e}"));
        assert_eq!(engine.content(), expected, "fixture {name} content drifted");
        assert!(engine.op_count() > 0);
    }
}
